### ISSUE TITLE
npm version is missing chalk in dependencies

### ISSUE THREAD

**Issue by matthiasdailey-ccri** [webpack-contrib/config-loader#8]
* Operating System: Ubuntu 16
* Node Version: 8.10.0
* NPM Version: 5.8.0
* webpack Version: 4.8.3
* config-loader Version: 1.1.1

I just updated some dependencies, which pulled in version 1.1.1 of this package.
I see that there was a [recent commit](https://github.com/webpack-contrib/config-loader/commit/ccf530362b627cdf9cccd7b3659af39d81b0c3cb) (3 hours ago) that sets chalk as a dependency.

The npm version of this package still has chalk as a peerDependency.
See dependencies listed on npmjs.com:
https://www.npmjs.com/package/@webpack-contrib/config-loader

Also, npm view output:
`⚡ npm view @webpack-contrib/config-loader@1.1.1`
```js
{ 
  // ...
  version: '1.1.1',
  // ...
  peerDependencies: { chalk: '^2.1.0', webpack: '^4.3.0' },
  dependencies: 
   { '@webpack-contrib/schema-utils': '^1.0.0-beta.0',
     cosmiconfig: '^5.0.2',
     'loud-rejection': '^1.6.0',
     'merge-options': '^1.0.1',
     resolve: '^1.6.0',
     'webpack-log': '^1.1.2' },
  devDependencies: 
   { '@commitlint/cli': '^6.1.3',
     '@commitlint/config-conventional': '^6.1.3',
     '@webpack-contrib/eslint-config-webpack': '^2.0.4',
     'babel-cli': '^6.26.0',
     'babel-core': '^6.26.0',
     'babel-plugin-transform-object-rest-spread': '^6.26.0',
     'babel-polyfill': '^6.26.0',
     'babel-preset-env': '^1.6.1',
     'babel-register': '^6.26.0',
     'conventional-github-releaser': '^2.0.2',
     'cross-env': '^5.1.4',
     del: '^3.0.0',
     'del-cli': '^1.1.0',
     eslint: '^4.19.1',
     'eslint-plugin-import': '^2.10.0',
     'eslint-plugin-prettier': '^2.6.0',
     esm: '^3.0.15',
     execa: '^0.10.0',
     expect: '^22.4.3',
     'flow-remove-types': '^1.2.3',
     husky: '^0.14.3',
     'jest-serializer-path': '^0.1.15',
     'jest-snapshot': '^22.4.3',
     'lint-staged': '^7.0.3',
     'memory-fs': '^0.4.1',
     minimist: '^1.2.0',
     mocha: '^5.0.5',
     nsp: '^3.2.1',
     nyc: '^11.6.0',
     'pre-commit': '^1.2.2',
     prettier: '^1.11.1',
     'standard-version': '^4.3.0',
     'ts-node': '^5.0.1',
     typescript: '^2.8.1',
     webpack: '^4.4.1',
     'webpack-defaults': '^2.3.0' },
  // ...
  }
```

And here is the error that it causes for me:
```
/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/@webpack-contrib/config-loader/lib/load.js:78
      log.error(chalk`An error ocurred while trying to load {grey ${configPath}}
                     ^

TypeError: chalk is not a function
    at module.exports (/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/@webpack-contrib/config-loader/lib/load.js:78:22)
    at module.exports (/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/@webpack-contrib/config-loader/lib/index.js:13:15)
    at load (/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/webpack-serve/lib/config.js:105:12)
    at module.exports (/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/webpack-serve/lib/options.js:62:10)
    at module.exports (/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/webpack-serve/index.js:16:10)
    at Object.<anonymous> (/opt/devel/src/asw-timeslider/asw-timeslider-ui/node_modules/webpack-serve/cli.js:82:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
```

**Comment by matthiasdailey-ccri** [comment]
@rynclark

**Comment by rynclark** [comment]
Yeah I got this yesterday too. Hopefully the next release where it's a direct dependency fixes this. // @matthiasdailey-ccri

**Comment by rynclark** [comment]
@matthiasdailey-ccri I just installed chalk as a dev dependency temporarily

**Comment by JRJurman** [comment]
is there a ETA for when this fix will this be published?

**Comment by shellscape** [comment]
![soon](https://img.memecdn.com/soon_o_273978.jpg)
